packages:
  - "apps/*"
  - "config/*"
  - "packages/*"
  - "examples/tests"
  - "examples/blog"
  - "examples/minimal"
  - "examples/startups"
  - "examples/ideas"
  - "examples/agents"
  - "examples/services"
  - "examples/waitlist"
  - "examples/website"
  - "examples/workflow"
  - "ai"
