name: 🔒 Fix lockfile conflicts on main

on:
  push:
    branches:
      - main
    paths:
      - 'pnpm-lock.yaml'
      - 'package.json'
      - '**/package.json'
  schedule:
    # Run daily at midnight UTC to ensure lockfile exists and is valid
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: write

jobs:
  fix-lockfile:
    runs-on: ubuntu-latest
    # Skip if this is a bot commit from the lockfile fix itself
    if: ${{ !contains(github.event.head_commit.message, '🔒') }}
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm CLI
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Check lockfile integrity
        id: lockfile-check
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "missing=true" >> $GITHUB_OUTPUT
            echo "❌ pnpm-lock.yaml is missing"
          elif pnpm install --frozen-lockfile --filter=!voice &>/dev/null; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "✅ pnpm-lock.yaml is valid"
          else
            echo "corrupted=true" >> $GITHUB_OUTPUT
            echo "🔧 pnpm-lock.yaml is corrupted or has conflicts"
          fi

      - name: Regenerate corrupted lockfile
        if: steps.lockfile-check.outputs.missing == 'true' || steps.lockfile-check.outputs.corrupted == 'true'
        run: |
          echo "🔧 Regenerating pnpm-lock.yaml from scratch"
          rm -f pnpm-lock.yaml
          pnpm install --no-frozen-lockfile --filter=!voice
          
          # Commit the fixed lockfile
          if [ -f pnpm-lock.yaml ]; then
            echo "✏️ Committing fixed pnpm-lock.yaml"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add pnpm-lock.yaml
            git commit -m "🔒 fix corrupted pnpm-lock.yaml on main branch"
            git push
          fi
