name: Prerelease

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
      - name: Publish preview (pkg.pr.new)
        run: pnpm dlx pkg-pr-new publish './packages/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
