name: Test

on:
  push:
    branches: ["**"]
  pull_request:

# Allow bot commits to trigger this workflow
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # Explicitly run even if triggered by a bot
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
        env:
          CI: true
          GITHUB_ACTIONS: true
          AI_GATEWAY_TOKEN: ${{ secrets.AI_GATEWAY_TOKEN }}
          AI_GATEWAY_URL: ${{ secrets.AI_GATEWAY_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}

